### ISSUE TITLE
Error when need create Tera-EU account

### ISSUE THREAD

**Issue by Hack-y** [Kloct/tera-auth-ticket#3]
Hi,

With the last update with Axiox, on the file eu.js the getLogin have error if no Tera-EU account.

```
01:58:01 Info: [tera-auth-ticket] Received Access Token!
01:58:01 Error: [client] TypeError: Cannot read property 'displayName' of undefined
    at webClient.getLogin (tera-client\node_modules\tera-auth-ticket\regions\eu.js:34:61)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async webClient.getLogin (tera-client\node_modules\tera-auth-ticket\index.js:28:28)
```

He should go into the "else": ` "No TERA-EU account found. Creating one."`, line 56 and create a new account before try to continue.

Can you fix it ?
Thank you

**Comment by Kloct** [comment]
Just fixed ccd73173 :+1:
thx for the report
